services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - postgres
      - redis
    environment:
      TELEGRAM_TOKEN:
      SUBSCRIBE_TELEGRAM_CHANNEL:
      SUBSCRIBE_TELEGRAM_CHANNEL_LINK:
      ADMIN_TELEGRAM_ID:
      POSTGRES_HOST: postgres
      POSTGRES_PORT:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      REDIS_HOST: redis
      REDIS_PORT:
  
  
  postgres:
    image: postgres:17.2
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_PORT:

  redis:
    image: redis:7.4.2
    restart: on-failure
    environment:
      REDIS_HOST:
      REDIS_PORT:

volumes:
  postgres-data:
